Updating Angela with SiQi
IMRCLab/workshop-aerial-swarms-rss2024 pull request #1
Opened 2024-06-10 12:26 UTC by knmcguire

2024-06-10 18:43 UTC, whoenig requested changes
One spelling mistake, otherwise it looks good.

2024-06-10 18:43 UTC, whoenig commented on index.html
> +        <li>17:00 - SiQi Zhou (on behalve of Angela Schoellig) </li>
behalf

2024-06-11 08:52 UTC, knmcguire commented on index.html
> +        <li>17:00 - SiQi Zhou (on behalve of Angela Schoellig) </li>
```suggestion
        <li>17:00 - SiQi Zhou (on behalf of Angela Schoellig) </li>
```

2024-06-11 08:53 UTC, knmcguire commented
Thanks! haha I did it correct the other time around. I've fixed it so I'll merge

2024-06-11 08:53 UTC, merged